config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :mains, only: [:index, :show]
  resources :characters, only: [:index, :new, :show, :create, :destroy, :update]

  get 'leaderboard', to: 'mains#leaderboard', as: :leaderboard

  get 'character_info/:id', to: 'characters#character_info', as: :character_info
  get 'all_of_my_character', to: 'characters#all_of_my_character', as: :all_of_my_character
  get 'character/:id/feeding', to: 'characters#feeding', as: :character_feeding
  get 'character/:id/activity', to: 'characters#activity', as: :character_activity
  get 'character/:id/playing', to: 'characters#playing', as: :character_playing

  post 'character/:id/feeding_process', to: 'characters#feeding_process', as: :feeding_process
  get 'character/:id/feeding_process', to: 'characters#feeding_deny'
  post 'character/:id/activity_process', to: 'characters#activity_process', as: :activity_process
  get 'character/:id/activity_process', to: 'characters#activity_deny'
  post 'character/:id/playing_process', to: 'characters#playing_process', as: :playing_process
  get 'character/:id/playing_process', to: 'characters#playing_deny'

  scope '/user' do
    get ':id/characters_history', to: 'characters#characters_history', as: :characters_history
  end

  scope '/info' do
    get 'guides/fed_state', to: 'guides#fed_state', as: :fed_state
    get 'guides/activity_require', to: 'guides#activity_require_level', as: :activity_require
    get 'guides/happiness', to: 'guides#happiness', as: :happiness
    get 'guides/age', to: 'guides#age', as: :age
    get 'guides/hibernated', to: 'guides#hibernated', as: :hibernated
    get 'guides/status', to: 'guides#status', as: :status

    get 'statics/about_us', to: 'statics#about_us', as: :about_us
    get 'statics/contact', to: 'statics#contact', as: :contact
    get 'statics/game_description', to: 'statics#game_description', as: :game_description
  end

  get 'admins_index', to: 'admins#index', as: :admins_index
  get 'account_management', to: 'admins#account_management', as: :account_management
  get 'character_management', to: 'admins#character_management', as: :character_management

  resources :admins, only:[:index] do
    collection do
      post :search, to: 'admins#search'
    end
  end

  scope '/admins' do
    get ':id/edit_user', to: 'admins#edit_user', as: :edit_user
    get ':id/edit_character', to: 'admins#edit_character', as: :edit_character
    patch ':id/user_update_by_admin', to: 'admins#user_update_by_admin', as: :user_update_by_admin
    patch ':id/character_update_by_admin', to: 'admins#character_update_by_admin', as: :character_update_by_admin
  end


  root to: 'mains#index'

end

app/views/admins/account_management.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Account Management</h4></li>
</br>
<div class="container mt-4">
  <%= form_tag(search_admins_path, class:"navbar-form", role: "search") do %>
    <div class="form-row">
      <div class="col-3"></div>
      <div class="col-6">
        <%= text_field_tag :search_params, nil, placeholder:"search in accounts", class:"form-control"%>
      </div>
      <div class="col-3">
        <div class="text-center">
          <%= submit_tag "Search User", class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center account_management_index mb-1 mt-5">
    <ul class="list-inline"><% @users.each do |user| %>
        <li class="list-inline-item mb-3" style="width:50px">Id: <%= user.id %></li>
        <li class="list-inline-item mb-3" style="width:320px">Email: <%= user.email %></li>
        <li class="list-inline-item mb-3" style="width:230px">Name:<%= user.name %></li>
        <li class="list-inline-item mb-3" style="width:180px">User since:<%= user.created_at.strftime("%F") %></li>
        <li class="list-inline-item mb-3" style="width:100px">Role:<%= user.role %></li>
        <li class="list-inline-item mb-3" style="width:85px">Active:<%= user.has_character %></li>
        <li class="list-inline-item mb-3" >
          <% if is_the_user_admin?(user) %>
            <%= link_to 'Show', edit_user_path(user.id), class: 'btn btn-outline-secondary' %></li>
          <% else %>
            <%= link_to 'Edit', edit_user_path(user.id), class: 'btn btn-outline-secondary' %></li>
          <% end %>
          </br>
      <% end %>
    </ul>
  </div>
</div>

<%= render 'shared/admin/back_for_admin_index' %>

app/views/admins/character_management.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Character Management</h4></li>
</br>


<div class="container mt-4">
  <%= form_tag(search_admins_path, class:"navbar-form", role: "search") do %>
    <div class="form-row">
      <div class="col-3"></div>
      <div class="col-6">
        <%= text_field_tag :search_params, nil, placeholder:"search in accounts", class:"form-control"%>
      </div>
      <div class="col-3">
        <div class="text-center">
          <%= submit_tag "Search Character", class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center account_management_index mb-1 mt-5">
    <ul class="list-inline"><% @characters.each do |character| %>
        <li class="list-inline-item mb-3" style="width:60px">Id: <%= character.id %></li>
        <li class="list-inline-item mb-3" style="width:230px">Name: <%= character.name %></li>
        <li class="list-inline-item mb-3" style="width:85px">Age: <%= character.age %></li>
        <li class="list-inline-item mb-3" style="width:140px">Born: <%= character.created_at.strftime("%F") %></li>
        <li class="list-inline-item mb-3" style="width:100px">Status:<%= character.status %></li>
        <% if alive_check(character) == true %>
          <li class="list-inline-item mb-3" style="width:150px; text-align:center">------</li>
        <% else %>
          <li class="list-inline-item mb-3" style="width:150px">Died: <%= character.died_on.strftime("%F") %></li>
        <% end %>
        <% if alive_check(character) == true %>
          <li class="list-inline-item mb-3" style="width:110px">Active: <%= active_character(character) %></li>
        <% else %>
          <li class="list-inline-item mb-3" style="width:110px; text-align:center">----</li>
        <% end %>
        <li class="list-inline-item mb-3" ><%= link_to 'Edit', edit_character_path(character.id), class: 'btn btn-outline-secondary' %></li>
        </br>
      <% end %>
    </ul>
  </div>
</div>

<%= render 'shared/admin/back_for_admin_index' %>

app/views/admins/edit_character.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Admin -  Edit Character</h4></li>

<div >
  <%= form_for @character, :url => { :action => "character_update_by_admin" } do |f| %>
    <div class="container mt-4">
      <div class="character_management_index">
        <div class="form-row">
          <div class="col-3"></div>
          <div class="col-6">

            <div class="form-group">

              <div class="form-group">
                <%= f.hidden_field :id, class:"form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class:"form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :age %>
                <%= f.text_field :age, class:"form-control", :disabled=>true %>
              </div>

              <div class="form-group">
                <% if alive_check(@character) == true%>
                  <%= f.label :status %>
                  <%= f.text_field :status, class:"form-control" %>
                  <div class="inline-group">
                    <%= f.label :happiness %>
                    <%= f.text_field :happiness, class:"form-control" %>
                    <%= f.label :fed_state %>
                    <%= f.text_field :fed_state, class:"form-control" %>
                    <%= f.label :activty %>
                    <%= f.text_field :activity_require_level, class:"form-control" %>
                  </div>
                <% else %>
                  <%= f.text_field :status, class:"form-control", :disabled=>true %>
                  <h6 class="text-muted mt-2">Died: <%= @character.died_on.strftime("%F") %></h6>
                <% end %>
              </div>

              <div class="form-group">
                  <%= f.label :owner %>
                  <%= f.text_field :owner_of_character, class:"form-control", :disabled=>true %>
              </div>

              <div class="form-group">
                <% if alive_check(@character) == true%>
                  <%= f.label :hibernated %>
                  <%= f.text_field :hibernated, class:"form-control" %>
                <% end %>
              </div>

            </div>
            <div class="col-3"></div>
          </div>
        </div>
      </div>
      </br>
      <div class="form-group text-center">
        <%= f.submit 'Save Character Details', class: 'btn btn-outline-secondary' %>
      </div>
  <% end %>
  </div>
</div>

<%= render 'shared/admin/back_for_characters_search' %>

app/views/admins/edit_user.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Admin -  Edit User</h4></li>

<div>
<%= form_for @user, :url => { :action => "user_update_by_admin" } do |f| %>
  <div class="container mt-4">
    <div class="form-row">
      <div class="col-3"></div>
      <div class="col-6">

        <div class="form-group">

          <div class="form-group">
            <%= f.label :id %>
            <%= f.text_field :id, class:"form-control", :disabled=>true %>
          </div>

          <div class="form-group">
            <%= f.label :name %>
            <%unless is_the_user_admin?(@user) %>
              <%= f.text_field :name, class:"form-control" %>
            <% else %>
              <%= f.text_field :name, class:"form-control", :disabled=>true %>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%unless is_the_user_admin?(@user) %>
              <%= f.text_field :email, class:"form-control" %>
            <% else %>
              <%= f.text_field :email, class:"form-control", :disabled=>true %>
            <% end %>
          </div>


          <div class="form-group">
            <% unless is_the_user_admin?(@user) %>
              <%= f.label :role %>
              <div class="text-center"
              <%= f.label :role, "Administrator", :value => "admin", :style => 'position:centre'  %>
              <%= f.radio_button :role, "admin" %>
              <%= f.label :role, "User", :value => "user", :style => 'position:centre'  %>
              <%= f.radio_button :role, "user", :checked => true %>
              </div>
            <% else %>
              <%= f.label :role %>
              <%= f.text_field :role, class:"form-control", :disabled=>true %>
            <% end %>
            </div>

        <div class="form-group">
          <%= f.label :budget %>
          <%unless is_the_user_admin?(@user) %>
            <%= f.text_field :budget, class:"form-control" %>
          <% else %>
            <%= f.text_field :budget, class:"form-control", :disabled=>true %>
          <% end %>
        </div>

        <div class="form-group text-center">
          <% unless is_the_user_admin?(@user) %>
            <%= f.submit 'Save User Details', class: 'btn btn-outline-secondary' %>
          <% else %>
            <h5 class="list-item text-center text-muted mt-4">You Can't edit an Admin user</h5>
          <% end %>
        </div>
      <% end %>
      </div>
    <div class="col-3"></div>
    </div>
  </div>
</div>

<%= render 'shared/admin/back_for_account_search' %>

app/views/admins/index.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Admin Panel</h4></li>
</br>
<div class="container index_content_container_admin">
    <div class="spacer_1_5"></div>
    <%= link_to "Account management", account_management_path, class: 'btn btn-outline-secondary btn-block' %>
    <%= link_to "Character management", character_management_path, class: 'btn btn-outline-secondary btn-block' %>
    </div>
  </div>
</div>

app/views/admins/search.html.erb
</br>
<% if @users.nil? == false %>
  <%= render "admins/search/account_search" %>
<% elsif @characters.nil? == false %>
  <%= render "admins/search/character_search" %>
<% end  %>

app/views/admins/show_character.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Admin: Show Character</h4></li>


<h4><%= @character %></h4>
<div>

app/views/admins/show_user.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Admin: Show User</h4></li>

<div>
<%= form_for @user, :url => { :action => "user_update_by_admin" } do |f| %>
  <div class="container mt-4">
    <div class="form-row">
      <div class="col-3"></div>
      <div class="col-6">

        <div class="form-group">

          <div class="form-group">
            <%= f.label :id %>
            <%= f.text_field :id, class:"form-control", :disabled=>true %>
          </div>

          <div class="form-group">
            <%= f.label :name %>
            <%unless is_the_user_admin?(@user) %>
              <%= f.text_field :name, class:"form-control" %>
            <% else %>
              <%= f.text_field :name, class:"form-control", :disabled=>true %>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%unless is_the_user_admin?(@user) %>
              <%= f.text_field :email, class:"form-control" %>
            <% else %>
              <%= f.text_field :email, class:"form-control", :disabled=>true %>
            <% end %>
          </div>


          <div class="form-group">
            <% unless is_the_user_admin?(@user) %>
              <%= f.label :role %>
              <div class="text-center"
              <%= f.label :role, "Administrator", :value => "admin", :style => 'position:centre'  %>
              <%= f.radio_button :role, "admin" %>
              <%= f.label :role, "User", :value => "user", :style => 'position:centre'  %>
              <%= f.radio_button :role, "user", :checked => true %>
              </div>
            <% else %>
              <%= f.label :role %>
              <%= f.text_field :role, class:"form-control", :disabled=>true %>
            <% end %>
            </div>

        <div class="form-group">
          <%= f.label :Active? %>
          <%= f.text_field :has_character, class:"form-control", :disabled=>true %>
        </div>

        <div class="form-group text-center">
          <% unless is_the_user_admin?(@user) %>
            <%= f.submit 'Save User Details', class: 'btn btn-outline-secondary' %>
          <% else %>
            <h5 class="list-item text-center text-muted mt-4">You Can't edit an Admin user</h5>
          <% end %>
        </div>
      <% end %>
      </div>
    <div class="col-3"></div>
    </div>
  </div>
</div>

<%= render 'shared/admin/back_from_admin_pages' %>