config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :mains, only: [:index, :show]
  resources :characters, only: [:index, :new, :show, :create, :destroy, :update]

  get 'leaderboard', to: 'mains#leaderboard', as: :leaderboard

  get 'character_info/:id', to: 'characters#character_info', as: :character_info
  get 'all_of_my_character', to: 'characters#all_of_my_character', as: :all_of_my_character
  get 'character/:id/feeding', to: 'characters#feeding', as: :character_feeding
  get 'character/:id/activity', to: 'characters#activity', as: :character_activity
  get 'character/:id/playing', to: 'characters#playing', as: :character_playing

  post 'character/:id/feeding_process', to: 'characters#feeding_process', as: :feeding_process
  get 'character/:id/feeding_process', to: 'characters#feeding_deny'
  post 'character/:id/activity_process', to: 'characters#activity_process', as: :activity_process
  get 'character/:id/activity_process', to: 'characters#activity_deny'
  post 'character/:id/playing_process', to: 'characters#playing_process', as: :playing_process
  get 'character/:id/playing_process', to: 'characters#playing_deny'

  scope '/user' do
    get ':id/characters_history', to: 'characters#characters_history', as: :characters_history
  end

  scope '/info' do
    get 'guides/fed_state', to: 'guides#fed_state', as: :fed_state
    get 'guides/activity_require', to: 'guides#activity_require_level', as: :activity_require
    get 'guides/happiness', to: 'guides#happiness', as: :happiness
    get 'guides/age', to: 'guides#age', as: :age
    get 'guides/hibernated', to: 'guides#hibernated', as: :hibernated
    get 'guides/status', to: 'guides#status', as: :status

    get 'statics/about_us', to: 'statics#about_us', as: :about_us
    get 'statics/contact', to: 'statics#contact', as: :contact
    get 'statics/game_description', to: 'statics#game_description', as: :game_description
  end

  get 'admins_index', to: 'admins#index', as: :admins_index
  get 'account_management', to: 'admins#account_management', as: :account_management
  get 'character_management', to: 'admins#character_management', as: :character_management

  resources :admins, only:[:index] do
    collection do
      post :search, to: 'admins#search'
    end
  end

  scope '/admins' do
    get ':id/edit_user', to: 'admins#edit_user', as: :edit_user
    get ':id/edit_character', to: 'admins#edit_character', as: :edit_character
    patch ':id/user_update_by_admin', to: 'admins#user_update_by_admin', as: :user_update_by_admin
    patch ':id/character_update_by_admin', to: 'admins#character_update_by_admin', as: :character_update_by_admin
  end


  root to: 'mains#index'

end

app/views/shared/_dinamic_single_index_back_button.html.erb
<section class="content-section text-muted text-center mt-1">

  <div class="container text-center">
    <div class="row mt-5">

      <div class="col-lg-5 col-md-7"></div>

      <div class="col-lg-2 col-md-7">
        <div class="action_arrow">
          <% if current_user %>
            <%= link_to 'Back', characters_path, class: 'btn btn-outline-secondary'%>
          <% else %>
            <%= link_to 'Back', mains_path, class: 'btn btn-outline-secondary'%>
          <% end %>
        </div>
        </br>
        <p class="list-inline-item small text-dark">Characters Page</p>
      </div>

      <div class="col-lg-5 col-md-7"></div>

    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<section class="content-section text-muted text-center">
  <div id="footer">
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
          <p class="text-center text-muted small">Dragon's Life | Adam Nemeth © All rights reserved</p>
        </div>
        <div class="col-lg-4"></div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_nav_for_guests.html.erb
<h1 class="display-4 font-weight-bold font-italic text-muted ml-2">Dragon's Life</h1>
<ul class="list-inline">
  <div class="row">
    <div class="col-md-4 ml-2">
      <li class="list-inline-item"><%= link_to 'Sign in', new_user_registration_path, class: 'btn btn-outline-secondary' %></li>
      <li class="list-inline-item"><%= link_to 'Log in', new_user_session_path, class: 'btn btn-outline-secondary' %></li>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-3 justify-content-center">
      <li class="list-inline-item"><%= link_to 'Guide', game_description_path, class: 'btn btn-outline-secondary' %></li>
      <li class="list-inline-item"><%= link_to 'Contact Us', contact_path, class: 'btn btn-outline-secondary' %></li>
      <li class="list-inline-item"><%= link_to 'About Us', about_us_path, class: 'btn btn-outline-secondary' %></li>
    </div>
  </div>
  </div>
</ul>
<hr>

app/views/shared/_nav_for_users.html.erb
<h1 class="display-4 font-weight-bold font-italic text-muted ml-2">Dragon's Life</h1>
<ul class="list-inline">
  <div class="row">
    <div class="col-md-4 ml-2">
      <li class="list-inline-item text-muted"><h5>Username: <%= current_user.name %></h5></li>
      <li class="list-inline-item"><%= link_to 'Sign Out', destroy_user_session_path, class: 'btn btn-outline-secondary', method: :delete %></li>
      <% if user_admin?(current_user) %>
        <% if @admin_path %>
          <li class="list-inline-item"><%= link_to 'Gaming page', characters_path, class: 'btn btn-outline-secondary'%></li>
        <% else %>
          <li class="list-inline-item"><%= link_to 'Admin index', admins_index_path, class: 'btn btn-outline-secondary'%></li>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3 ml-1 pl-5"><h5 class="font-weight-bold font-italic text-muted ml-4 mt-1">Wallet:  <%= @amount %> Gold</h5></div>
    <div class="col-md-3 ml-5 pl-5">
      <%= link_to 'Guide', game_description_path, class: 'btn btn-outline-secondary' %>
      <%= link_to 'Contact Us', contact_path, class: 'btn btn-outline-secondary' %>
      <%= link_to 'About Us', about_us_path, class: 'btn btn-outline-secondary' %>
    </div>
  </div>
  </div>
</ul>
<hr>