config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :mains, only: [:index, :show]
  resources :characters, only: [:index, :new, :show, :create, :destroy, :update]

  get 'leaderboard', to: 'mains#leaderboard', as: :leaderboard

  get 'character_info/:id', to: 'characters#character_info', as: :character_info
  get 'all_of_my_character', to: 'characters#all_of_my_character', as: :all_of_my_character
  get 'character/:id/feeding', to: 'characters#feeding', as: :character_feeding
  get 'character/:id/activity', to: 'characters#activity', as: :character_activity
  get 'character/:id/playing', to: 'characters#playing', as: :character_playing

  post 'character/:id/feeding_process', to: 'characters#feeding_process', as: :feeding_process
  get 'character/:id/feeding_process', to: 'characters#feeding_deny'
  post 'character/:id/activity_process', to: 'characters#activity_process', as: :activity_process
  get 'character/:id/activity_process', to: 'characters#activity_deny'
  post 'character/:id/playing_process', to: 'characters#playing_process', as: :playing_process
  get 'character/:id/playing_process', to: 'characters#playing_deny'

  scope '/user' do
    get ':id/characters_history', to: 'characters#characters_history', as: :characters_history
  end

  scope '/info' do
    get 'guides/fed_state', to: 'guides#fed_state', as: :fed_state
    get 'guides/activity_require', to: 'guides#activity_require_level', as: :activity_require
    get 'guides/happiness', to: 'guides#happiness', as: :happiness
    get 'guides/age', to: 'guides#age', as: :age
    get 'guides/hibernated', to: 'guides#hibernated', as: :hibernated
    get 'guides/status', to: 'guides#status', as: :status

    get 'statics/about_us', to: 'statics#about_us', as: :about_us
    get 'statics/contact', to: 'statics#contact', as: :contact
    get 'statics/game_description', to: 'statics#game_description', as: :game_description
  end

  get 'admins_index', to: 'admins#index', as: :admins_index
  get 'account_management', to: 'admins#account_management', as: :account_management
  get 'character_management', to: 'admins#character_management', as: :character_management

  resources :admins, only:[:index] do
    collection do
      post :search, to: 'admins#search'
    end
  end

  scope '/admins' do
    get ':id/edit_user', to: 'admins#edit_user', as: :edit_user
    get ':id/edit_character', to: 'admins#edit_character', as: :edit_character
    patch ':id/user_update_by_admin', to: 'admins#user_update_by_admin', as: :user_update_by_admin
    patch ':id/character_update_by_admin', to: 'admins#character_update_by_admin', as: :character_update_by_admin
  end


  root to: 'mains#index'

end

app/models/character.rb
class Character < ActiveRecord::Base

  belongs_to :user

  validates :name, length: { maximum: 25 }
  validates :name, :fed_state, :happiness, :activity_require_level, :status, presence: true
  validates :name, uniqueness: true
  validates :user_id, presence: true

  def self.age_order_filter
    order(:age => :desc)
  end

  def self.age_order_alive_filter
    order(:age => :desc).where(status:"alive")
  end

  def self.character_in_asc_id_order
    order(:id => :asc)
  end

  def self.characters_history_order_logic
    order(:status => :asc, :id => :desc)
  end

  def self.limited_desc_ordered_characters
    all.order(:age => :desc).limit(10)
  end

  #unused
  def self.current_users_character(user)
    where.not(user_id:user.id)
  end

  def owner_of_character
    self.user.name
  end

  def self.active_living_characters
    where(status:'alive',hibernated:false, manualy_hibernated:false)
  end

  def character_is_dying
    self.update_attributes(status:'dead',
                           died_on: Time.now)
  end

  def simulated_time_passed_updated
    current_fed_state = self.fed_state
    current_activity_require_level = self.activity_require_level
    current_happiness = self.happiness
    current_age = self.age
    self.update_attributes(fed_state: fed_limit(current_fed_state -= 1).fed_level_min_setter,
                           activity_require_level: activity_limit(current_activity_require_level += 2).activity_level_max_setter,
                           happiness: happiness_limit(current_happiness -= 1).happiness_level_min_setter,
                           age: current_age + 1)
  end

  def activity_require_level_decrease_with(decreased_with)
    decreased_value = self.activity_require_level.to_i + decreased_with
    accepted_decreased_value = activity_limit(decreased_value).activity_level_min_setter
    self.update_attributes(activity_require_level:accepted_decreased_value)
  end

  def activity_require_level_increased_with(increased_with)
    increased_value = self.activity_require_level.to_i + increased_with
    accepted_increased_value = activity_limit(increased_value).activity_level_max_setter
    self.update_attributes(activity_require_level:accepted_increased_value)
  end

  def fed_state_increase_with(increased_with)
    increased_value = self.fed_state.to_i + increased_with
    accepted_increased_value = fed_limit(increased_value).fed_level_max_setter
    self.update_attributes(fed_state:accepted_increased_value)
  end

  def happiness_decreased_with(decreased_with)
    decreased_value = self.happiness.to_i + decreased_with
    accepted_decreased_value = happiness_limit(decreased_value).happiness_level_min_setter
    self.update_attributes(happiness:accepted_decreased_value)
  end

  def happiness_increase_with(increased_with)
    increased_value = self.happiness.to_i + increased_with
    accepted_increased_value = happiness_limit(increased_value).happiness_level_max_setter
    self.update_attributes(happiness:accepted_increased_value)
  end

  private

  def fed_limit(points)
    CharactersServices::DataFieldLimitSetter.new(points)
  end

  def activity_limit(points)
    CharactersServices::DataFieldLimitSetter.new(points)
  end

  def happiness_limit(points)
    CharactersServices::DataFieldLimitSetter.new(points)
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_action :set_character_details_with_owner_filter, only: [:show,
                                                                 :destroy,
                                                                 :update,
                                                                 :feeding,
                                                                 :feeding_process,
                                                                 :feeding_deny,
                                                                 :activity,
                                                                 :activity_deny,
                                                                 :activity_process,
                                                                 :playing,
                                                                 :playing_deny,
                                                                 :playing_process]

  before_action :authenticate_user!
  before_action :alive_check, only: [:show,
                                     :feeding,
                                     :feeding_deny,
                                     :feeding_process,
                                     :activity,
                                     :activity_deny,
                                     :activity_process,
                                     :playing,
                                     :playing_deny,
                                     :playing_process,
                                     :update]


  rescue_from ActiveRecord::RecordNotFound, with: :no_character_exist_rescue

  def index
    @characters = Character.limited_desc_ordered_characters
    @my_character = @characters.where(user_id: current_user.id, status:'alive').first
  end

  def all_of_my_character
    @characters = Character.where(user_id: current_user.id).order(:id => :desc)
  end

  def characters_history
    if params[:id].to_i == current_user.id
      redirect_to all_of_my_character_path
    else
      @owner_of_character = User.find_by(id:params[:id])
      @owners_characters = Character.where(user_id:@owner_of_character.id).characters_history_order_logic
    end
  end

  def show

  end

  def feeding

  end

  def feeding_deny
    redirection_to_character_path(@character,'alert', I18n.t('characters.action_alerts.could_not_finish_meal'))
  end

  def feeding_process
    @current_amount = params[:amount].to_i
    @spendable_amount = -1*(@current_user.wallet.amount - @current_amount)
    @current_fed_state = params[:fed_state]
    @current_activity_state = params[:activity_require_level]
    @current_happiness_state = params[:happiness]
    @costs = wallet_view - @current_amount
    if not_enough_available_activity_points?
      redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.you_can_not_move'))
    else
      if paying_service_budget_check?(@spendable_amount) == true
        @sent_potion_of_food = -1*(@character.fed_state.to_i - @current_fed_state.to_i)
        @sent_points_of_activity = -1*(@character.activity_require_level.to_i - @current_activity_state.to_i)
        @sent_happiness_points = -1*(@character.happiness.to_i - @current_happiness_state.to_i)
      else
        redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.low_on_gold'))
      end
    end
  end

  def activity

  end

  def activity_deny
    redirection_to_character_path(@character,'alert', I18n.t('characters.action_alerts.could_not_finish_training'))
  end

  def activity_process
    @current_amount = params[:amount]
    @current_fed_state = params[:fed_state]
    @current_activity_state = params[:activity_require_level]
    @current_happiness_state = params[:happiness]
    @earn = -1*(wallet_view - @current_amount.to_i)
    if not_enough_available_activity_points?
      redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.you_can_not_move'))
    elsif not_enough_available_feeding_points?
      redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.you_can_not_eat'))
    else
      @sent_potion_of_food = -1*(@character.fed_state.to_i - @current_fed_state.to_i)
      @sent_points_of_activity = -1*(@character.activity_require_level.to_i - @current_activity_state.to_i)
      @sent_happiness_points = -1*(@character.happiness.to_i - @current_happiness_state.to_i)
    end
  end

  def playing

  end

  def playing_deny
    redirection_to_character_path(@character,'alert', I18n.t('characters.action_alerts.could_not_finish_playing'))
  end

  def playing_process
    @current_amount = params[:amount].to_i
    @spendable_amount = -1*(@current_user.wallet.amount - @current_amount)
    @current_fed_state = params[:fed_state]
    @current_activity_state = params[:activity_require_level]
    @current_happiness_state = params[:happiness]
    @costs = wallet_view - @current_amount
    if not_enough_available_activity_points?
      redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.you_can_not_move'))
    elsif not_enough_available_feeding_points?
      redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.you_can_not_eat'))
    else
      if paying_service_budget_check?(@spendable_amount) == true
        @sent_potion_of_food = -1*(@character.fed_state.to_i - @current_fed_state.to_i)
        @sent_points_of_activity = -1*(@character.activity_require_level.to_i - @current_activity_state.to_i)
        @sent_happiness_points = -1*(@character.happiness.to_i - @current_happiness_state.to_i)
      else
        redirection_to_character_path(@character,'warning', I18n.t('characters.action_warnings.low_on_gold'))
      end
    end
  end

  def update
    if path_recogniser == 'feeding'
      update_fed_state(@character)
    elsif path_recogniser == 'activity'
      update_activity_state(@character)
    elsif path_recogniser == 'playing'
      update_playing_state(@character)
    end
  end

  def new
    if alive_check_for_create_character
      redirection_to_characters_path('alert', I18n.t('characters.action_alerts.you_have_character_alive'))
    else
      Character.new
    end
  end

  def create
    if alive_check_for_create_character
      redirection_to_characters_path('alert',I18n.t('characters.action_alerts.you_have_character_alive'))
    else
      @character = Character.new(character_params)
      update_user_has_character_field(current_user)
      if @character.save
        WalletServices::BasicWalletCreator.new(current_user).setup_starter_amount
        redirection_to_character_path(@character,'notice', I18n.t('characters.action_notices.character_has_born'), @character.name)
      else
        flash.now[:alert] = I18n.t('characters.action_alerts.something_went_wrong_on_character_creation')
        render :new
      end
    end
  end

  def destroy
    current_character = @character
    if @character.delete
      redirection_to_characters_path('warning', I18n.t('characters.action_warnings.character_has_been_destroyed'), current_character.id)
    else
      redirection_to_characters_path('alert', I18n.t('characters.action_alerts.something_went_wrong_on_character_destroying'), current_character.id)
    end
  end

  def character_info
    @character = Character.find(params[:id])
    @user = @character.user
  end

  private

  def set_character_details_with_owner_filter
    @character = Character.find(params[:id])
    if @character.user_id != current_user.id
      redirection_to_characters_path('alert', I18n.t('characters.action_alerts.that_character_is_not_yours'))
    end
  end

  def character_params
    params.require(:character).permit(:id,
                                      :user_id,
                                      :name,
                                      :status,
                                      :age,
                                      :happiness,
                                      :fed_state,
                                      :activity_require_level)
  end

  def update_fed_state(character)
    if character.update_attributes(:fed_state => fed_limit.fed_level_max_setter,
                                   :activity_require_level => activity_limit.activity_level_min_setter,
                                   :happiness => happiness_limit.happiness_level_max_setter)

      if character.fed_state == 100
        redirection_to_character_path(character,'warning', I18n.t('characters.action_warnings.you_can_not_eat_more'))
      else
        redirection_to_character_path(character,'notice', I18n.t('characters.action_notices.feeding_action_has_been_proceed'))
      end
      paying_service_proceed
    else
      redirection_to_character_path(character,'alert', I18n.t('characters.action_alerts.un_success_feeding_process'))
    end
  end

  def update_activity_state(character)
    if character.update_attributes(:fed_state => fed_limit.fed_level_max_setter,
                                   :activity_require_level => activity_limit.activity_level_min_setter,
                                   :happiness => happiness_limit.happiness_level_max_setter)
        paying_service_proceed
        redirection_to_character_path(character,'notice', I18n.t('characters.action_notices.activity_action_has_been_proceed'))
    else
      redirection_to_character_path(character,'alert', I18n.t('characters.action_alerts.un_success_activity_process'))
    end
  end

  def update_playing_state(character)
    if character.update_attributes(:fed_state => fed_limit.fed_level_max_setter,
                                   :activity_require_level => activity_limit.activity_level_min_setter,
                                   :happiness => happiness_limit.happiness_level_max_setter)
      if character.happiness == 100

app/helpers/characters_helper.rb
module CharactersHelper

  include Services::DateTransformer

  def life_length_counter(character)
    if character.status == 'alive'
      length = Time.now - character.created_at
      result(length)
    else
      length = (character.created_at - character.died_on).abs
      result(length)
    end
  end

  def params_builder_of_action(character,wallet,fed_points,cost,happiness_points,activity_points,source)
    params_of_fed_state = character.fed_state + fed_points
    params_of_happiness = character.happiness + happiness_points
    params_of_activity = character.activity_require_level + activity_points
    params_of_amount = wallet + cost

    {fed_state: params_of_fed_state,
     amount: params_of_amount,
     happiness: params_of_happiness,
     activity_require_level: params_of_activity,
     extra: source}
  end

  def params_builder_of_action_process(fed_state,amount,activity_state,happiness_state,source)
    {fed_state: fed_state,
     amount: amount,
     activity_require_level: activity_state,
     happiness: happiness_state,
     extra: source }
  end

  def formated_time_layout(full_days,hours)
    "#{full_days} Days and #{hours} Hours"
  end

  def amount_of_cost_on_actions(amount)
    "Going to Cost: #{amount} Gold"
  end

  def amount_of_earn_on_actions(amount)
    "Going to Get: #{amount} Gold"
  end

  private

  def result(seconds)
    hours = seconds.to_i / SECOND_IN_A_HOUR
    full_days = hours_to_full_days(hours)
    hours = rest_of_hours(hours)
    formated_time_layout(full_days,hours)
  end

end

app/views/characters/activity_process.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Activity - Action Path</h4></li>

<section class="content-section text-center mt-5 mb-5">
  <div class="container pt-5 mt-5 mb-5">
    <div class="row mt-5 mb-5">
      <div class="col-lg-3 col-md-7"></div>
      <div class="col-lg-6 col-md-7">
        <table class="table table-sm table-borderless text-secondary">
          <thead>
          <tr>
            <th>Fed State: <%= @character.fed_state %></th>
            <th>Activity Require: <%= @character.activity_require_level %></th>
            <th>Happiness: <%= @character.happiness %></th>
          </tr>
          </thead>

          <tbody>
          <tr>
            <td>Lose-able: <%= @sent_potion_of_food %></td>
            <td>Lose-able: <%= @sent_points_of_activity %></td>
            <td>Claim-able: <%= @sent_happiness_points%></td>
          </tr>
          </tbody>
        </table>

        <%= render 'characters/shared/amount_on_process'  %>

        <div class="col-lg-3 col-md-7"></div>
      </div>
    </div>
  </div>
</section>

<div class="spacer_1 pb-5"></div>

<section class="content-section mt-5 text-muted text-center">

  <div class="container mt-5 text-center">
    <div class="row mt-5">

      <div class="col-lg-4 col-md-7"></div>
      <div class="col-lg-2 col-md-7">
        <div class="action_arrow mb-3">
          <%= link_to 'Back', character_path(@character), class: 'btn btn-outline-secondary' %>
        </div>
        <p class="list-inline-item small text-dark">Characters Page</p>
      </div>

      <div class="col-lg-2 col-md-7">
        <div class="action_arrow mb-3">
          <%= button_to 'Claim', character_path(@character.id, params_builder_of_action_process(@current_fed_state,
                                                                                                @current_amount,
                                                                                                @current_activity_state,
                                                                                                @current_happiness_state,
                                                                                                'from_activity_process' )), id:'claim_button', disabled: false, :remote => true, class: 'btn btn-outline-secondary', :method => :put %>
        </div>
        <p class="list-inline-item small text-dark">Claim your Points</p>
      </div>
      <div class="col-lg-4 col-md-7"></div>

    </div>
  </div>

</section>

<!--<script>-->
<!--    setTimeout(function(){-->
<!--        $('#claim_button').removeAttr('disabled');-->
<!--    }, <%= (@sent_points_of_activity.to_i)*1000 %> );-->
<!--</script>-->

app/views/characters/all_of_my_character.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4 pb-1">Your characters history</h4></li>
</br>
<div class="container index_content_container">
  <div class="row justify-content-center mt-1">
    <% if @characters.empty? %>
      <ul class="list">
        <li class="list-inline-item">You have no Character!</li>
        <li class="list-inline-item"><%= link_to "Create one now", new_character_path, class: 'btn btn-outline-secondary btn-block' %></li>
      </ul>
      </br>
      </br>
      <div class="spacer_2_5"></div>
    <% else %>
      <ul class="list-inline"><% @characters.each do |character| %>
          <li class="list-inline-item mb-3" style="width:220px">Name: <%= character.name %></li>
          <li class="list-inline-item mb-3" style="width:80px">Age: <%= character.age %></li>
          <li class="list-inline-item mb-3" style="width:100px">Status: <%= character.status %></li>
          <% if character.status == 'alive' %>
            <%= link_to 'Go', character_path(character.id, {extra: 'from_all_of_my_character'}), class: 'btn btn-outline-secondary mb-1', style:"width:50px"%>
          <% else %>
            <li class="list-inline-item mb-3" >This Character has died on: <%= date_view_optimizer(character.updated_at) %></li>
            <li class="list-inline-item mb-3" >Accurate life length:  <%= life_length_counter(character) %></li>
          <% end %>
          </br>
        <% end %>
        </br>
    <% end  %>
    </ul>
  </div>
</div>

<div class="spacer_1_5"></div>

<%= render 'shared/dinamic_single_index_back_button' %>

app/views/characters/character_info.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Character Information</h4>
<section class="content-section mt-5 mb-5 text-muted text-center">
  <div class="container mt-5 mb-5">
    <div class="spacer_1"></div>
  <h6>Character: <%= @character.name %></h6>
    <div class="spacer_0_5"></div>
    <ul class="list-inline mb-5">
      <li class="list-inline-item">Age Of Character: <%= @character.age %></li>
      <li class="list-inline-item">Status:<%= @character.status %></li>
      <li class="list-inline-item">Fed State:<%= @character.fed_state %></li>
      <li class="list-inline-item">Activity:<%= @character.activity_require_level %></li>
      <li class="list-inline-item">Happiness:<%= @character.happiness %></li>
      <li class="list-inline-item mb-3" >Accurate life length:  <%= life_length_counter(@character) %></li>
    </ul>
  </div>

</section>

<div class="spacer_3"></div>

<section class="content-section mt-5 text-muted text-center">

<div class="container mt-5 text-center">
  <div class="row mt-5">

    <div class="col-lg-4 col-md-7"></div>
    <div class="col-lg-2 col-md-7">
      <div class="action_arrow">
        <p><%= link_to 'Back', characters_path, class: 'btn btn-outline-secondary'%></p>
      </div>
      <p class="list-inline-item small text-dark">Characters Page</p>
    </div>

    <div class="col-lg-2 col-md-7">
      <div class="action_arrow">
        <p><%= link_to 'Go', characters_history_path(@user.id), class: 'btn btn-outline-secondary'%></p>
      </div>
      <p class="list-inline-item small text-dark">Owner info</p>
    </div>
    <div class="col-lg-4 col-md-7"></div>

  </div>
</div>

</section>

app/views/characters/index.html.erb
<div class="container index_content_container">
  <div class="row mt-3">

    <div class="col-lg-4 col-md-7 pr-5 border-right">
      <ul class="list text-center">
        <% if @my_character.nil? %>
          <li class="list-inline-item text-muted"><h4>You have no living Character!</h4></li>
          <div class="row mt-4 text-center">
            <div class="col-lg-2 col-md-7"></div>
            <div class="col-lg-8 col-md-7">
              <div class="action_arrow pt-4">
                <p><%= link_to 'Create', new_character_path, class: 'btn btn-outline-secondary p-3 main_action_button' %></p>
              </div>
              <p class="list-inline-item small text-dark">Create one now</p>
            </div>
            <div class="col-lg-2 col-md-7"></div>
          </div>
        <% else %>
          <li class="list-item text-center mb-5"><h4 class="text-muted">Your Active Character:</h4></li>
          <li class="list-item mb-3">Name: <%= @my_character.name %></li>
          <li class="list-item mb-3">Age: <%= @my_character.age %></li>
          <li class="list-item mb-3">Happiness: <%= @my_character.happiness %></li>
          <li class="list-item mb-3">Fed_state: <%= @my_character.fed_state %></li>
          <li class="list-item mb-3">Activity_require <%= @my_character.activity_require_level %></li>
        <%end %>
      </ul>
    </div>

    <div class="col-lg-8 col-md-7 pl-5 list_of_character">
      <h4 class="list-item text-center mb-4 text-muted">LeaderBoard:</h4></li></br>
      <div class="list_of_character">
        <ul class="list">
          <%@characters.each_with_index do |character,index| %>
            <li class="list-inline-item" style="width:40px"><%= index + 1  %></li>
            <li class="list-inline-item" style="width:280px">Name: <%= character.name %></li>
            <li class="list-inline-item" style="width:110px">Age: <%= character.age %></li>
            <li class="list-inline-item" style="width:110px">Status: <%= character.status %></li>
            <li class="list-inline-item mx-auto img-fluid small_arrow">
              <%= link_to 'Go', character_info_path(character.id, {extra: 'from_index'}), class: 'btn btn-outline-secondary mb-1'%>
            </li>
            </br>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="row mt-1 text-center">


    <% if @my_character.nil? %>

      <div class="col-lg-1 col-md-7"></div>
      <div class="col-lg-2 col-md-7">
        <div class="action_arrow">
          <p><%= link_to 'Go', all_of_my_character_path({extra: 'from_index'}), class: 'btn btn-outline-secondary p-3 main_action_button' %></p>
        </div>
        <p class="list-inline-item small text-dark">My Characters History</p>
      </div>
      <div class="col-lg-1 col-md-7"></div>

    <% else %>

      <div class="col-lg-2 col-md-7">
        <div class="action_arrow">
          <p><%= link_to 'Go', character_path(@my_character.id, {extra: 'from_index'}), class: 'btn btn-outline-secondary p-3 main_action_button' %></p>
        </div>
        <p class="list-inline-item small text-dark">Character Training</p>
      </div>

      <div class="col-lg-2 col-md-7">
        <div class="action_arrow">
          <p><%= link_to 'Go', all_of_my_character_path({extra: 'from_index'}), class: 'btn btn-outline-secondary p-3 main_action_button' %></p>
        </div>
        <p class="list-inline-item small text-dark">My Characters History</p>
      </div>

    <% end %>

    <div class="col-lg-3 col-md-7"></div>


    <div class="col-lg-2 col-md-7">
      <div class="action_arrow pt-4">
        <p><%= link_to 'Go', leaderboard_path({extra: 'from_index'}), class: 'btn btn-outline-secondary' %></p>
      </div>
      <p class="list-inline-item small text-dark">Expanded Leaderboard</p>
    </div>
    <div class="col-lg-4 col-md-7"></div>


  </div>

</div>

app/views/characters/show.html.erb
</br>
<h4 class="list-item text-center text-muted mt-4">Actions Page</h4></li>

<section class="content-section text-center text-secondary">
<div class="container pt-3">
<ul class="list-inline">
  <li class="list-inline-item"><h6>Name Of Character: <%= @character.name %></h6></li></br>
  <li class="list-inline-item"><h6>Age Of Character: <%= @character.age %></h6></li></br></br>
  <li class="list-inline-item"><h6>Fed State: <%= @character.fed_state %></h6></li>
  <li class="list-inline-item"><h6>Activity require: <%= @character.activity_require_level %></h6></li>
  <li class="list-inline-item"><h6>Happiness: <%= @character.happiness %></h6></li>
</ul>
</div>
</section>

<section class="content-section text-faded text-center mt-5 mb-3">
  <div class="container mt-4 mb">
    <div class="row">
      <div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
        <div class="action_image_3">
          <li class="list-inline-item">
          <%= link_to image_tag('menu/icons8-restaurant-50.png'), character_feeding_path(@character) %>
          </li>
        </div>
        <h5 class="mt-4 action_image_text">
          <%= link_to 'Feeding', fed_state_path, class: 'btn btn-outline-secondary mb-1'%>
        </h5>
        <p class="text-secondary mb-0">Main: Fed State </p>
        <p class="text-secondary mb-0">Secondary: Happiness </p>
        <p class="text-secondary mb-0">Loses: Activity Require</p>
        </br>
        <strong><p class="text-secondary mb-0">Pay with Gold service</p></strong>
      </div>


      <div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
        <div class="action_image_3">
          <li class="list-inline-item">
          <%= link_to image_tag('menu/icons8-trainers-50.png'), character_activity_path(@character) %>
          </li>
        </div>
        <h5 class="mt-4 action_image_text">
          <%= link_to 'Activity', activity_require_path, class: 'btn btn-outline-secondary mb-1'%>
        </h5>
        <p class="text-secondary mb-0">Main: Activity Require  </p>
        <p class="text-secondary mb-0">Secondary: Happiness </p>
        <p class="text-secondary mb-0">Loses: Fed State </p>
        </br>
        <strong><p class="text-secondary mb-0">Earn Gold with it</p></strong>
      </div>

      <div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
        <div class="action_image_3">
          <li class="list-inline-item">
            <%= link_to image_tag('menu/icons8-soccer-ball-50.png'), character_playing_path((@character)) %>
          </li>
        </div>
        <h5 class="mt-4 action_image_text">
          <%= link_to 'Happiness', happiness_path, class: 'btn btn-outline-secondary mb-1'%>
        </h5>
        <p class="text-secondary mb-0">Main: Happiness  </p>
        <p class="text-secondary mb-0">Secondary: Activity Require </p>
        <p class="text-secondary mb-0">Loses: Fed State </p>
        </br>
        <strong><p class="text-secondary mb-0">Pay with Gold service</p></strong>
      </div>
    </div>
  </div>
</section>

<section class="content-section mt-5 text-muted text-center">

  <div class="container mt-5 text-center">
    <div class="row mt-5">

      <div class="col-lg-5 col-md-7"></div>

      <div class="col-lg-2 col-md-7">
        <div class="action_arrow pt-4">
          <p><%= link_to 'Back', characters_path, class: 'btn btn-outline-secondary' %></p>
        </div>
        <p class="list-inline-item small text-dark">Characters Page</p>
      </div>

      <div class="col-lg-5 col-md-7"></div>

    </div>
  </div>
</section>

<!-- <p><%= link_to 'Destroy your character', character_path(@character), method: :delete, data: {confirm: "Are you sure"}, class:"float-right", style: 'color:red' %></p> -->

</br>